### ISSUE TITLE
Extract Reader View into its own component

### ISSUE THREAD

**Issue by robert-baldwin** [robert-baldwin/reader-app#4]
My attempts to extract [`readerView()`](https://github.com/robert-baldwin/reader-app/blob/248577d32c37fba619cb76038cbf8a63fa1dc32f/packages/client/reader-app/reader-app.ts#L53-L75) into `reader-view.ts` have failed due to a JSON parsing issue from within lit-element upon calling `render()` on the newly extracted component.

**Comment by gdbaldw** [comment]
Done as a commit. More work to make separate file, but thought you'd like to see the minimal change needed. Notice that dot (.) preceding the attribute name indicates passing the property. See https://lit-element.polymer-project.org/guide/templates . Also, I found that by running "yarn iterate" in a seperate console (outside of VS Code), CI works much better.

**Comment by gdbaldw** [comment]
Second commit extracts to its own file.

**Comment by robert-baldwin** [comment]
Thank you for your contribution @gdbaldw ! 🎉
